# Generated by Django 5.2.8 on 2025-12-26 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_followupquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followupchoice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('followupchoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.followupquestion')),
            ],
        ),
    ]
