# Generated by Django 5.2.8 on 2025-12-31 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_followupchoices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followupquestion',
            options={'ordering': ['pub_date']},
        ),
        migrations.RenameField(
            model_name='followupchoices',
            old_name='followupchoice_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='followupquestion',
            old_name='followupquestion_text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='followupchoices',
            name='followupchoice',
        ),
        migrations.AddField(
            model_name='followupchoices',
            name='related_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.followupquestion'),
        ),
        migrations.AlterField(
            model_name='followupquestion',
            name='followupquestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_questions', to='polls.question'),
        ),
    ]
