# Generated by Django 5.2.9 on 2026-01-24 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_followupquestion_path_count_question_path_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followupquestion',
            name='followupquestion',
        ),
        migrations.AddField(
            model_name='followupquestion',
            name='parent_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_questions', to='polls.choice'),
        ),
        migrations.AddField(
            model_name='followupquestion',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_branch', to='polls.question'),
        ),
    ]
