# Generated by Django 5.2.9 on 2026-01-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_followupquestion_followupquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='branches',
            field=models.IntegerField(default=0),
        ),
    ]
